version: '3.7'
services: 
    fastapi:
        container_name: fastapi
        build: backend
        restart: always
        command: uvicorn main:app --host 0.0.0.0 --root-path="/api"
    # api:
    #     container_name: api
    #     build: app-test
    #     restart: always
    #     command: uvicorn main:app --host 0.0.0.0 --root-path="/api"
    nginx:
        depends_on: 
            - fastapi
        container_name: proxy-app
        build: 
           context: frontend
           args:
            #   - API_URL=http://localhost:8000/api
              - API_URL=/api
        ports: 
            - "3000:80"
        restart: always
        volumes:
            - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        