version: '3.7'
services: 
    fastapi:
        container_name: fastapi
        build: backend
        restart: always
    nginx:
        depends_on: 
            - fastapi
        container_name: proxy-app
        build: frontend
        ports: 
            - "8000:80"
        restart: always
        